* scsh_adventures
** what is it?
   collection of scsh scripts to perform some funny or tedious tasks
*** general
    --help should work (i hate assholes who don't support it)
*** wstaw.scm
    takes a path to an image as an argument, and posts it to
    [[http://wstaw.org/][wstaw.org]] image hosting service. i recommend using `-p' option, so
    that it's "private", meaning it will not show up on the front page
    aggregator. there are also tags and comments, but who cares.

    oh, and it requires [[http://curl.haxx.se/][curl]].
** what is it for?
   inspired by [[http://www.jwz.org/hacks/][jwz's hacks collection]] and sometimes non obvious fact
   that humans are not computers, i realized that it's a romantic idea
   to make computers do stuff for me. i'm not sure if thanks to them,
   i'll save more time than i wasted writing them (or this readme, for
   that matter), but at least this makes it clear who is the
   dominating side in my polyamorous relationships with computers.
** is it any good for me?
   no, because these are scsh scripts, and you probably don't care
   enough to install scsh interpreter.
   i'm a terrible scheme/scsh programmer anyway.
** wait, what? why scsh? what the hell is that anyway?
   why scsh? let me get this straight -- you write (ba|)sh scripts and
   you ask why scsh? what is it, repressed memory? Stockholm syndrome?
** acknowledgments
   who should i thank? my so-called ``colleagues,'' who laugh at
   me behind... oh, um, sorry for that. i'd like to thank Olin Shivers
   and the rest of scsh team for making it all possible.
** license
   do with it whatever you want, i'll be happy if you let me know that
   you find it interesting (i hope you do and this will make you stop
   writing shell scripts), or that you use it (some of them are
   actually useful! how crazy is that!)
** author
   Adam Michalik <adam@michalik.es>
